source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EmojiConstants_Example', :exclusive => true do
  pod "EmojiConstants", :path => "../"
end

target 'EmojiConstants_Tests', :exclusive => true do
  pod "EmojiConstants", :path => "../"

  
end
